#!/bin/bash
# Script to test K3s cluster functionality

echo "=== Testing K3s Cluster ==="
echo "1. Connecting to bastion host: 54.216.57.242"
echo "2. From bastion, SSH to K3s server: 10.0.3.200"
echo "3. Commands to run on K3s server:"
echo ""
echo "# Check cluster nodes"
echo "sudo kubectl get nodes"
echo ""
echo "# Check all resources"
echo "sudo kubectl get all --all-namespaces"
echo ""
echo "# Deploy nginx pod"
echo "sudo kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml"
echo ""
echo "# Verify nginx pod"
echo "sudo kubectl get pods"
echo "sudo kubectl get all --all-namespaces | grep nginx"
echo ""
echo "=== SSH Commands ==="
echo "ssh -i your-key.pem ec2-user@54.216.57.242"
echo "ssh -i your-key.pem ec2-user@10.0.3.200"