name: Trigger Jenkins Pipeline

on:
  push:
    branches: [ main, task_6 ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Get Jenkins Crumb
        id: get_crumb
        run: |
          # Получаем crumb (токен CSRF) от Jenkins.
          # Используем JENKINS_USER и JENKINS_TOKEN для аутентификации.
          # Вывод будет в формате "Jenkins-Crumb:ВАШ_ТОКЕН_CRUMB".
          CRUMB=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" "${{ secrets.JENKINS_URL }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          echo "crumb=$CRUMB" >> $GITHUB_OUTPUT
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }} # Убедитесь, что этот секрет добавлен в GitHub
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }} # Это токен API Jenkins

      - name: Trigger Jenkins Pipeline
        run: |
          # Используем полученный crumb для запуска билда.
          # Передаем crumb как отдельный заголовок.
          # Аутентификация через user:token с флагом -u.
          curl -X POST \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            -H "${{ steps.get_crumb.outputs.crumb }}" \
            "${{ secrets.JENKINS_URL }}/job/flask-app-pipeline/build"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }} # Убедитесь, что этот секрет добавлен в GitHub
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }} # Это токен API Jenkins
